[project]
authors = [
  "Georgios Delkos <georgios.delkos@ourovoros.io>",
  "Henry Baldwin <henry@stork.xyz>",
]
entry = "main.sw"
license = "Apache-2.0"
name = "stork"

[dependencies]
std = { git = "https://github.com/fuellabs/sway", tag = "v0.68.4" }
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.7.0" }
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.25.2" }
stork_sway_sdk = { path = "../../../../sdks/fuel/stork-sway-sdk" }

[proxy]
enabled = true
address = "0x4b26da4f9d2e102177906075e9d729980228a54ee927a055df461b6c6c7798d3"
